# apiVersion: v1
# kind: pod
# metadata: 
#    name:  nginx
# space:
#   containers:
#   # docker run  -d --name nginx nginz
#   -name: nginx
#   images: nginx



apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  # docker run -d --name nginx nginx
  - name: nginx
    image: nginx
    
