apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod-messages
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html


#       kind: Pod
# apiVersion: v1
# metadata:
#   name: multi-container
# spec:
#   containers:
#   - name: nginx
#     image: nginx
#   - name: almalinux
#     image: almalinux:9
#     command: ["sleep","1000"]