# apiVersion: v1
# kind: Pod
# metadata:
#   name: annotations-demo
#   annotations:
#     imageregistry: "https://hub.docker.com/"
# spec:
#   containers:
#   - name: nginx
#     image: nginx:1.14.2
#     ports:
#     - containerPort: 80


kind: Pod
apiVersion: v1
metadata:
  name: annotations
  annotations:
    imageregistry: "https://hub.docker.com/"
    buildURL: "https://jenkins.joindevops.com/expense/backend/build/67"
spec:
  containers:
   - name: nginx
b    image: nginx