# apiVersion: v1
# kind: Pod
# metadata:
#   name: annotations-demo
#   annotations:
#     imageregistry: "https://hub.docker.com/"
# spec:
#   containers:
#   - name: nginx
#     image: nginx:1.14.2
#     ports:
#     - containerPort: 80


# kind: Pod
# apiVersion: v1
# metadata:
#   name: annotations
#   annotations:
#     imageregistry: "https://hub.docker.com/"
#     buildURL: "https://jenkins.joindevops.com/expense/backend/build/67"
# spec:
#   containers:
#    - name: nginx
# b    image: nginx


apiVersion: v1
kind: Pod
metadata:
  name: annotations
  annotations:
    name: myapp
    project: expense
    environment: dev
    using: K8
    URL: "https://hub.docker.com/_/node"
    imageURL: "https://hub.docker.com/_/node/docker_hub.com"
    resourceName: annotations
    details: "we can give annotations as lenghty way of details and URLs and image URLs and anything and there is no limitations here"
spec:
  containers:
    - name: nginx
      image: nginx